### ISSUE TITLE
Pagination : can't find this : Showing X to X of X Entries

### ISSUE THREAD

**Issue by JamalSaid** [jamesdordoy/laravel-vue-datatable#102]
hello,

i want to show this div  "  Showing X to X of X Entries "in the bottom of the table .

may table 👍

`        <data-table
                ref="UserTable"
                url="api/user"
                order-dir= "desc"
                :per-page="perPage"
                :columns="columns"
                :classes="classes"
                >
                <tbody v-if="data" class="text-center" slot="body" slot-scope="{ data }">
                <tr 
                    :key="item.id"
                    v-for="item in data">                    
                    <td 
                        :key="column.name"
                        v-for="column in columns">
                        <data-table-cell
                          :value="item"
                          :name="column.name"
                          :meta="column.meta"
                          :event="column.event"
                          :handler="column.handler"
                          :comp="column.component"
                          :classes="column.classes">
                        </data-table-cell>

                        <slot v-if="column.label == 'Actions'">
                            <a href="#"  @click="editModel(item)" title="Update">
                                <i class="fa fa-edit text-primary mr-2 "></i>
                            </a>
                            <a href="#" @click="deleteUser(item.id)" title="Delete">
                                <i class="fa fa-trash  text-danger "></i>
                            </a>
                        </slot>
                        
                    </td>
                </tr>
            </tbody>
            <tbody v-else class="text-center" slot="body">
              
                <span class="text-center">No Data Found</span>
               
            </tbody>
            </data-table>`

pLease Sir Somehelp i need to konw the total of Users.

**Comment by JamalSaid** [comment]
fixed with your awesome Code  : 

<data-table
    :url="url"
    :columns="columns">
    <div slot="pagination" slot-scope="{ links = {}, meta = {} }">
        <nav class="row">
            <div class="col-md-6 text-left">
                <span>
                    Showing {{meta.from}} to {{meta.to}} of {{ meta.total }} Entries
                </span>
            </div>
            <div class="col-md-6 text-right">
                <button
                    :disabled="!links.prev"
                    class="btn btn-primary"
                    @click="url = links.prev">
                    Prev
                </button>
                <button
                    :disabled="!links.next"
                    class="btn btn-primary ml-2"
                    @click="url = links.next">
                    Next
                </button>
            </div>      
        </nav>
    </div>
</data-table>

Thank you Bro :)

**Comment by edwingromero** [comment]
How do I change the language of "Showing X to X of X Entries"
