### ISSUE TITLE
Pagination on top?

### ISSUE THREAD

**Issue by cedricpri** [jamesdordoy/laravel-vue-datatable#103]
Hi! First of all, thanks for this package, it works great.

I do have a suggestion though: as I plan on making a table with around 50 rows per page, I would like to have the possibility to add the pagination slot both at the top and at the bottom of the page. This would allow the user to navigate through the different pages without having to scroll down first. 

As far as I know, it's not currently possible to do this. Do you think adding such a feature might be interesting? Thanks!

**Comment by jamesdordoy** [comment]
Hi @cedricpri,

I haven't tested if this is possible but ill add it to the next release.

Thanks,
