### ISSUE TITLE
Sort arrows always active

### ISSUE THREAD

**Issue by cedricpri** [jamesdordoy/laravel-vue-datatable#104]
Hi! 

So I think I just found a small bug, present in your example [https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters](url). When you try to sort any given column, one of the arrow gets slightly darker, as expected. However, when ordering a second column after the first one, the first column arrow stays active even though we are not ordering based on this first column any more and there is apparently no way to reset it. Obviously, in the example mentioned it doesn't really matter as the different between an active and unactive arrow is not obvious, but I have personally changed the css for the active-filter-asc classes and this makes the issue a bit more visible.

I guess fixing it should be quite easy and I tried to see if I could fix it myself. However, being relatively new to web development and to vue JS I actually did not manage to find the origin of this small issue. I'm not sure why this line [https://github.com/jamesdordoy/laravel-vue-datatable/blob/master/src/components/DataTableTh.vue#L19]/url) is not working as expected. Maybe you can help me with this?

Thanks a lot!

**Comment by jamesdordoy** [comment]
Hi @cedricpri,

Yes I'm aware of this issue. It'll be fixed with the next release.

Thanks,

**Comment by jamesdordoy** [comment]
Hi @cedricpri,

This has been addressed under the 0.6.0 release.

Thanks,

James

**Comment by cedricpri** [comment]
Great, thanks a lot!
