### ISSUE TITLE
Aggregating related models supported ?

### ISSUE THREAD

**Issue by ipimpat** [jamesdordoy/laravel-vue-datatable#112]
Is sort etc. supported when aggregating related models ?

https://laravel.com/docs/8.x/eloquent-relationships#counting-related-models

**Comment by jamesdordoy** [comment]
Hi @ipimpat,

No its not supported. This could potentially be added but would also include some backend changes.

**Comment by muarachmann** [comment]
Is there any improvements on this? @jamesdordoy

**Comment by jamesdordoy** [comment]
Hi @muarachmann,

I'm open to PR's but do not have the time to implement.

Apologies

**Comment by felixgoldstein** [comment]
+1
