### ISSUE TITLE
New Release ETA

### ISSUE THREAD

**Issue by muarachmann** [jamesdordoy/laravel-vue-datatable#129]
Hi there, just wish to know when you plan on releasing a new update as per #114 , I have tried installing from source directly but keep running to a number of errors nothing below works

```
npm install github:jamesdordoy/laravel-vue-datatable#master
npm install jamesdordoy/laravel-vue-datatable#master
```
Right now this is the only package in my repo with high vuln and I really wish to bypass this
```
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

added 8 packages, and audited 1040 packages in 5s

94 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by jamesdordoy** [comment]
Hey @muarachmann,

Next week ill be working over the package

**Comment by muarachmann** [comment]
> Hey @muarachmann,
> 
> Next week ill be working over the package

Hi @jamesdordoy thanks so much for your prompt response I will hold off my anticipated release till next week then :)

**Comment by mua-rachmann** [comment]
@jamesdordoy any improvements on this?
