### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by moathOSA** [jamesdordoy/laravel-vue-datatable#152]
is this package support datatable buttons ? 
like copy, pdf , csv , hide columns ??

is this package support the checkbox column ??

@jamesdordoy

**Comment by jamesdordoy** [comment]
Hello @moathOSA,

You could implement those features yourself using ajax and slots.

I'm going to close this and also recommend you use a different vue table package at the moment as i don't have anytime to support this until next year and ill properly do a Vue3 rewrite.
