### ISSUE TITLE
Concat two columns data

### ISSUE THREAD

**Issue by redleon00** [jamesdordoy/laravel-vue-datatable#160]
Hi, i'm using laravel-vue-datatable but i don't know how i can concat two columns from the data, how i can do it?

**Comment by jamesdordoy** [comment]
Hey @redleon00,

from memory, you can do that using the `transform` property when defining a column [https://github.com/jamesdordoy/laravel-vue-datatable#column-props](https://github.com/jamesdordoy/laravel-vue-datatable#column-props)

e.g. 
```
{
 name: 'first_name',
 label: 'Full Name',
 transform: (row) => { return row.first_name + ' ' + row.last_name }
}
```

Shout if that dosnt work but think it should

**Comment by redleon00** [comment]
Thx u @jamesdordoy  for your response, ok i this moment i resolve ir using a map function with the data but i will try your solution.

**Comment by redleon00** [comment]
`transform: ({data}) => { return data.owner.name + ' ' + data.owner.last_name }`

That is the solution, only have to change row for data and the braquets, thx u @jamesdordoy
