### ISSUE TITLE
How remove Page Select and input finder

### ISSUE THREAD

**Issue by redleon00** [jamesdordoy/laravel-vue-datatable#161]
Hi, i don't need page select and the input finder, how i con that?.. i tried using ccs but i don't have success

**Comment by jamesdordoy** [comment]
Hey @redleon00,

Read the docs here: [https://v2.vuejs.org/v2/guide/components-slots.html](https://v2.vuejs.org/v2/guide/components-slots.html), [https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters](https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters)
