### ISSUE TITLE
How to create Expanded Data ? 

### ISSUE THREAD

**Issue by pimenlabs** [jamesdordoy/laravel-vue-datatable#166]
hi, I'm going to make a feature of expanding data in a table, but I don't see any documentation that talks about that. can you give directions?

**Comment by jamesdordoy** [comment]
Hey @pimenlabs,

U need to use the body slot and create your own logic and html around the expanding row.

Ive looked over the docs but havent used or updated this package in a while. If your using vue 2, it should work fine but id look at other packages for the time being such as [https://vanilla-components.com/guide/components/datatable.html](https://vanilla-components.com/guide/components/datatable.html). I havent used it personally but it looks awesome :)

**Comment by pimenlabs** [comment]
Hey @jamesdordoy,
when can you update this package to add child row features?

**Comment by jamesdordoy** [comment]
You can already achieve this functionality, refer to my previous comment:

[https://github.com/jamesdordoy/laravel-vue-datatable/blob/master/src/components/DataTable.vue#L46](https://github.com/jamesdordoy/laravel-vue-datatable/blob/master/src/components/DataTable.vue#L46)

[https://v2.vuejs.org/v2/guide/components-slots.html](https://v2.vuejs.org/v2/guide/components-slots.html)

**Comment by pimenlabs** [comment]
can you give me sampel ?
