### ISSUE TITLE
Decency on  vulnerable versions of axios

### ISSUE THREAD

**Issue by emarcus255** [jamesdordoy/laravel-vue-datatable#170]
Great component but the latest version shows as vulnerable.

` 
 laravel-vue-datatable  *
  Depends on vulnerable versions of axios
  node_modules/laravel-vue-datatable
`

@jamesdordoy Any chances for updating them please?

**Comment by jamesdordoy** [comment]
Hey @emarcus255,

Sadly no, im going to archive this repo soon as Vue2 is EOL.

Feel free to fork and update them yourself.
