### ISSUE TITLE
Slot to customise datatable body

### ISSUE THREAD

**Issue by TheLizzan** [jamesdordoy/laravel-vue-datatable#22]
Hi,
I'm trying to override the datatable body using the body slot as detailed in https://github.com/jamesdordoy/Laravel-Vue-Datatable#overriding-the-datatable-body but I cannot get it to work - the slot doesn't seem to be picked up at all. 

I'm very new to both Laravel and Vue, so it might very well be my poor understanding, but from looking at the source I can't find a slot for the table body at all. 
Might I be missing something? I have the 0.3.7 version installed via npm.

This is the code I'm using - changing anything between the tbody tags makes no difference.

    <data-table url="/orders/json/" class="lista table" :per-page="perPage" :columns="headings" sort="default_sort_order" dir="desc">
      <tbody slot="body" slot-scope="{ data }">
        <tr
          :key="item.id"
          v-for="item in data">
          <td 
            :key="column.name"
            v-for="column in columns">
            <data-table-cell
              :value="item"
              :name="column.name"
              :meta="column.meta"
              :event="column.event"
              :handler="column.handler"
              :comp="column.component"
              :classes="column.classes">
            </data-table-cell>
          </td>
        </tr>
      </tbody>
    </data-table>

**Comment by jamesdordoy** [comment]
Hello,

This is because i haven't published an update to NPM for this functionality. I wanted to get a some unit tests in place before publishing and document how to override the body.

I'll get a new version published today and update the documentation.

Apologies for any confusion caused.

**Comment by jamesdordoy** [comment]
This should be corrected in 0.3.11.

**Comment by TheLizzan** [comment]
Thank you very much! I've just tried it and it seem to work perfectly for me.
