### ISSUE TITLE
Laravel Eloquent Relation

### ISSUE THREAD

**Issue by clien007** [jamesdordoy/laravel-vue-datatable#23]
Hi!

I just to ask how to display the related data using **_with_** function in eloquent? Here's my sample data:

id: 4, 
first_name: "Michael Capistrano", 
last_name: "test",
email: "mykel_019@yahoo.com"
user_role_matrix:{
         id: 1, 
         user_id: 4, 
         role_id: 1, 
        created_at: "2019-09-27 16:03:53", 
        user_role: {
                 id: 1
                 role_code: "ROL0001"
                 role_name: "Admin"

**Comment by jamesdordoy** [comment]
Hello,

This isn't possible using the current API but I have pushed an update so this can be done.

Please upgrade your package to `0.3.12` and then you can access your relationships using the dot notation e.g.

`role.name`

Let me know if this solves your issue

Thanks

**Comment by jamesdordoy** [comment]
Closed due to inactivity.
