### ISSUE TITLE
any example to pass data to a modal by pressing a button? I need to edit some datas from it by passing an id.

### ISSUE THREAD

**Issue by Javier1995** [jamesdordoy/laravel-vue-datatable#24]

**Comment by jamesdordoy** [comment]
Hey, I will create a an example on the docs for this tomorrow.

To summarize shortly, you can use a normal click event found [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/injecting-dynamic-components) and then keep track of the current id using local component data e.g.

``` javascript
data() {
 return {
  modalId: 0,
 }
},
methods: {
  updateModalId(data) {
   this.modalId = data.id;
  }
 }
}
```

The modal id or data can be parsed directly to the modal using props and will update accordingly.

**Comment by jamesdordoy** [comment]
I've added an example to the docs that can be found [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/modal)

Let me know if this solves your issue.

**Comment by Javier1995** [comment]
Fantastic! It has a better performance than the one  I already did, thank you.
