### ISSUE TITLE
Reload table

### ISSUE THREAD

**Issue by clien007** [jamesdordoy/laravel-vue-datatable#25]
Hi! How can I reaload the table manually or via button? Thanks!

**Comment by jamesdordoy** [comment]
Hey,

This can be achieved using a Vue.JS ref found [here](https://vuejs.org/v2/api/#ref).

Assign a reference to your table `ref="myTable"` you can then access the methods of the component and refresh the data `this.$refs.myTable.getData()`

Alternatively, you can update the tables URL prop which will force a re-render but this may be harder to maintain.

Let me know if this solves your issue.

**Comment by jamesdordoy** [comment]
Closed due to inactivity.
