### ISSUE TITLE
Sorting Float Columns

### ISSUE THREAD

**Issue by casahuga** [jamesdordoy/laravel-vue-datatable#26]
So thank you for this amazing component, currently we are trying to sort the column table that is a float, but is not sorting correctly. Do you know if is an issue with the component or a Laravel issue?

**Comment by jamesdordoy** [comment]
Hey,

Thank you for your nice comment, hugely appreciate it.

I haven't tested the component with a float value before, would you mind posting a couple of example values i can seed into my database specifically to see if i can replicate the issue?

Thank for letting me know :)

**Comment by casahuga** [comment]
Hey,

Some example value example: 7.2, 6.92, 7.32, 6.1. It order as you see.

Thanks

**Comment by jamesdordoy** [comment]
Hey,

I've tested the table with some random data and your values but the column sorting appears to be working correctly.

I did a little more digging and noticed that when using the default filtering method e.g.

`$query = User::dataTableQuery($column, $orderBy, $searchValue);`

The scoped query requires the columns to specified in the model. 

```php
protected $dataTableColumns = [
    'id' => [
        'searchable' => false,
    ],
    'name' => [
        'searchable' => true,
    ],
    'email' => [
        'searchable' => true,
    ],
    'yourFloatColumn' => [
        'searchable' => true,
    ],
];
```

For column filtering, this doesn't seems necessary as this is controllable on the table component.

I have pushed a new release to the [composer package](https://github.com/jamesdordoy/Laravel-Vue-Datatable_Laravel-Package/releases/tag/1.1.2) 1.1.2 that will remove that requirement or alternatively you can remain 1.1.1 and specify the float column in your model.

Let me know if this solves your issue,

**Comment by casahuga** [comment]
Amazing!

It's just that, thank you so much.
