### ISSUE TITLE
Delete row

### ISSUE THREAD

**Issue by casahuga** [jamesdordoy/laravel-vue-datatable#27]
Hey,

We are trying to delete a row, using a custom button like this:

{
                                label: '',
                                name: 'Edit',
                                filterable: false,
                                component: ButtonComponent,
                                event: "click",
                                handler: this.displayRow,
                                dataTotal: this.tableData,
                                classes: {
                                        'btn': true,
                                        'btn-primary': true,
                                        'btn-sm': true,
                                },
                        },

How can we delete the row inside the component? 

Thank you

**Comment by jamesdordoy** [comment]
Hey,

Based on the above example, you will need to add a method `this.displayRow` or whatever your preferred named would be to the methods object of your component instance.

Also that button function will need to send an AJAX request to delete the row to your Laravel backend. At that point you will need to reload the table. This can be achieved using a Vue.JS ref found here.

Assign a reference to your table `ref="myTable"` you can then access the methods of the component and refresh the data `this.$refs.myTable.getData()`

Alternatively, you can update the tables URL prop which will force a re-render but this may be harder to maintain.

**Comment by casahuga** [comment]
Perfect solution, thank you so much 😊
