### ISSUE TITLE
Show date/time in local timezone

### ISSUE THREAD

**Issue by hrodenburg** [jamesdordoy/laravel-vue-datatable#28]
Hi,

Not really a bug at all, but I am wondering if there is a way to modify the data in a column before showing it.

In my case, I'm displaying an table which contains a date/time column. The non-vue way I'm converting to local timezone is using Carbon in the blade template (I'm using Laravel). It seems [moment.js](https://momentjs.com) is a nice library to handle the formatting, but I don't understand how to do this using laravel-vue-table. Is is possible to call a function which wil alter the data?
Offcourse, I can alter the api to show the dates in local timezone, but I prefer to do this in the frontend.
I'm quite new to vue, so I might overlook or didn't understand something, thanks for understanding.

Thanks in advance,
Hugo

**Comment by jamesdordoy** [comment]
Hey Hugo,

There is indeed, have a look at the documentation for [injecting components](https://jamesdordoy.github.io/laravel-vue-datatable/examples/injecting-dynamic-components).

You can inject a component to format the date values e.g.

```
<template>
    <span> {{ data[name]|formatDate }} </span>
</template>

<script>
export default {
    props: {
        data: {},
        name: {},
        click: {},
        classes: {},
    }
}
</script>
```

The syntax for formatting the date above `formatDate` is a [Vue.js filter](https://vuejs.org/v2/guide/filters.html). Give that a glance and you can see an example filter below for your implementation:

```
//Filters
Vue.filter('formatDate', function(value, format='Do MMMM YYYY') {
    if (value) {
        return moment(String(value)).format(format)
    }
    return 'N/A'
});
```

As you mentioned your using Laravel, this will go in your app.js file before your vue instance is initialised.

Let me know if thats clear enough or if you need further explanation.

Thanks for creating the issue.

**Comment by hrodenburg** [comment]
Hi James,

Thank you for your excellent, detailed and fast answer! Much appreciated!

I just put this together and and it works perfectly well, this is exactly what i needed (I will have to tweak the format, but I'm sure that won't be a problem).

I've did read the docs before about using components (inlcuding vuejs filters as well some time ago) but I guess I just needed some directions on how to put it all together, but it totally makes sense now I see how it is done.

Thanks!

**Comment by IsidroMar95** [comment]
I'm in the same situation, how can I implement it? the explanation is not very clear to me. I just created the `DataTableDateCell` component and inside I put this code

```
<template>
    <span> {{ data[name]|formatDate }} </span>
</template>

<script>
    export default {
        name: "DataTableDateCell",
        props: {
            data: {
                type: Object,
                default: () => ({})
            }
        },
        computed: {}
    }
</script>
```

how can i return the date like _**14 de Marzo de 2020**_ in in local timezone
