### ISSUE TITLE
default column order direction

### ISSUE THREAD

**Issue by hrodenburg** [jamesdordoy/laravel-vue-datatable#29]
Hi,

I'm sorry to bother you again. I would like to show a table default ordered by id in "desc" direction. The default behaviour is to sort on the "id" column (which is fine in this case) in ascending direction. It might be something obvious, but I just cannot figure out how to alter that default behaviour. Is this possible?

Regards,
Hugo

**Comment by TheLizzan** [comment]
Fantastic @jamesdordoy! I've just run into the same issue myself, needing a default sort on a different column in a descending direction.

**Comment by jamesdordoy** [comment]
Hey all,

I've published a new version `0.3.16` that adds a new table prop `order-dir`. This can be set to `asc`, `desc`

The docs have been updated appropriately.

Let me know if anything is not working correctly.

**Comment by hrodenburg** [comment]
Thanks a lot James! I will test tomorrow and let you know
