### ISSUE TITLE
Custom default order column

### ISSUE THREAD

**Issue by TheLizzan** [jamesdordoy/laravel-vue-datatable#30]
Hi James,
Maybe I'm missing something, but is there any way to set the default column to sort the table by? I'd like to default sort neither by id or the first column in the table.

**Comment by jamesdordoy** [comment]
Hey @TheLizzan 

No you are correct, there is no way to specify what column the table should be order by by default.

I have just pushed an update `0.3.17` that adds in a new table prop named `order-by`. You can use this to specify what column name will be used as the initial ordering.

Let me know if that is sufficient.

**Comment by TheLizzan** [comment]
Thank you @jamesdordoy! That is exactly what I needed. I might have found a bug though; if the first column name isn't "id", the sort still seems to fall back on the first column name for me.

**Comment by jamesdordoy** [comment]
Hey @TheLizzan,

You are correct about the above bug. Sorry i hadn't commented earlier but i was ill. Expect this corrected tomorrow.

Thanks for letting me know

**Comment by jamesdordoy** [comment]
Should be corrected in 0.3.18.

Now the first column name will be selected by default as an index order for the table order by request.

**Comment by TheLizzan** [comment]
That's perfect! Thank you ever so much, and I hope you're feeling better now. :)
