### ISSUE TITLE
clear filter value

### ISSUE THREAD

**Issue by vaniok010** [jamesdordoy/laravel-vue-datatable#31]
Hi, I have two related filters: "County" and "District". The "District" depends on the "County". How can I clear the "District" filter when receiving new districts list?

```javascript methods: {  
	updateDistricts: function (tableData) {   
		let vm = this;
		axios.post('/get-districts', {county: tableData.filters.county})
			.then(function (response) {
				vm.districts = response.status === 200 ? response.data : [];
				// tableData.filters.district = ''; //this is not working
                        })
	       },
       }`

**Comment by jamesdordoy** [comment]
Hey,

Based on your above example you are missing the vm variable you set above e.g. `vm.tableData.filters.district`

I would recommend looking into arrow functions for JavaScript as this would remove that variable entirely e.g.

```js
axios.post('/get-districts', {county: tableData.filters.county})
	.then(response => {
		vm.districts = response.status === 200 ? response.data : [];
		this.tableData.filters.district = ''; //this is not working
         });
```

Let me know if you need more information or if this isn't the issue.
