### ISSUE TITLE
Error in render: "Column Not Found Exception: The column isDiscontinued was not found"

### ISSUE THREAD

**Issue by demiryasinoruc** [jamesdordoy/laravel-vue-datatable#32]
When i use boolean field with **false** value, i am getting this error, **true** values works normal

**Comment by jamesdordoy** [comment]
Hey @demiryasinoruc 

That exception is thrown when the column name is not found in the data for the table.

I suggest looking at chrome dev tools and what is being sent back from your backend.

If your using Laravel, maybe have a look to see if the relationship is nested. If so, please use the dot notation e.g.

`user.role.isDiscontinued`

Let me know if you need more help with your issue.

**Comment by demiryasinoruc** [comment]
But true values working well, i can see true values on the table and isDiscontinued not in the another object

![Data](https://user-images.githubusercontent.com/937795/67525398-4fd22480-f6bb-11e9-8c58-15e7829f2264.png)

**Comment by demiryasinoruc** [comment]
@jamesdordoy by the way if i change the data boolen to string (like "true" or "false") it's working

**Comment by jamesdordoy** [comment]
Awesome thanks for the screen shots, i will try to replicate and correct this over the weekend,

**Comment by jamesdordoy** [comment]
Hey,

I've pushed a new release `0.3.19` that should correct this bug.

The row was not being correctly tested for boolean values as you have shown above.

Let me know if this solves your issue.
