### ISSUE TITLE
How to pass some props to External component

### ISSUE THREAD

**Issue by rohitbahekar** [jamesdordoy/laravel-vue-datatable#34]
I am creating component which shows image and **I want to pass an url prefix to component  as a prop** to get image working
Note: The table data only contains image name. 
Please guide me how to do that
![1](https://user-images.githubusercontent.com/57762527/68868507-a7ddd300-071d-11ea-904f-e71a0bc359bf.PNG)
![2](https://user-images.githubusercontent.com/57762527/68868508-a7ddd300-071d-11ea-8dc4-f28b9b8d58a1.PNG)

**Comment by jamesdordoy** [comment]
Hello,

You can parse additional data to the component using the `meta` property on each column e.g.

``` js
export default {
    data() {
        return {
            columns: [
                {
                    label: '',
                    name: 'View',
                    filterable: false,
                    component: ExampleButton,
                    meta: {
                        url: BASE_URL
                    }
                },
            ]
        }
    },
    components: {
        // eslint-disable-next-line
        ExampleButton,
    },
}
```

You can then accept the meta prop in your custom component e.g.

``` js
props: ['data', 'meta'],
```

and access the url value under this.meta.url

More information can be found in the [README](https://github.com/jamesdordoy/laravel-vue-datatable#column-props)

Let me know if this solves your issue.

**Comment by jamesdordoy** [comment]
Closed due to inactivity
