### ISSUE TITLE
Can't figure out how to join tables

### ISSUE THREAD

**Issue by belardip** [jamesdordoy/laravel-vue-datatable#35]
If I join tables I get an error because each table has an "id" column, even if i give an alias to each "id" column. 
If I use eloquent to make a relationship I'm no longer able to search or sort by those columns.

What's the best way to work around this?

**Comment by jamesdordoy** [comment]
Hey @belardip,

I have replicated your issue locally but i am unable to produce a fix to the problem.

I can see ideally you would like to be able to sort and search related data in the same table but this is not possible as the current implementation of the package is using eloquent.

It could be possible with a package rewrite but that would also include changing the API and i having investigating the changes further, There isn't a clean way to discover all relationships on a model without using PHP 7+ and the Reflection API and this implementation isn't perfect either.

My recommendation would be to implement your own custom solution as a package wont be able to join your tables automatically or find the correct "name" or "id" column across two tables anyway.

Apologies this isn't a solution but the current package wasn't designed with related column sorting and searching in mind.

**Comment by jamesdordoy** [comment]
Hey @belardip,

I have come up with a solution to allow for table joining with filtering and searching.

I will be pushing a new version `0.4.0` later today with an example on the documentation.

**Comment by jamesdordoy** [comment]
`0.4.0` is now published on npm. Please update your npm package and also update your composer package to `1.2.0`

You can find an example implementation on the documentation [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/joins)

Let me know if you need any further examples or if you find any issues.

**Comment by jamesdordoy** [comment]
Closed due to inactivity.
