### ISSUE TITLE
customise the column data

### ISSUE THREAD

**Issue by Nayanika15** [jamesdordoy/laravel-vue-datatable#36]
how can i customise the value fetched eg if I get 1 in a field i want it to be displayed as 'completed' and if 0 I want it to be displayed as 'incomplete' ?

**Comment by jamesdordoy** [comment]
Hey @Nayanika15,

This can be achieved by injecting a component into the table. You can find more information [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/injecting-dynamic-components).

For example, you could parse the following component into the column in question and "Complete" and "Incomplete" will be rendered based on the row value.

> CompleteIncomplete.vue
``` html
<template>
    <p> {{ data.complete ? "Complete" : "Incomplete"  }} </p>
</template>
```

``` js
export default {
    props: {
        data: {},
    }
}
```
> Datatable.vue

``` js
import CompleteIncomplete from './CompleteIncomplete.vue';

export default {
    data() {
        return {
            columns: [
                ...
                {
                    label: 'Complete',
                    name: 'complete',
                    filterable: false,
                    component: CompleteIncomplete, 
                },
            ]
        }
    }
}
```

Let me know if that solves your issue.

**Comment by jamesdordoy** [comment]
Closed due to inactivity.
