### ISSUE TITLE
Issue with post data search

### ISSUE THREAD

**Issue by Jean45612** [jamesdordoy/laravel-vue-datatable#38]
Hello, i have a problem when I send a value in my input for search. 
here is my http request
http://127.0.0.1:8000/api/roles?search=Postulante&dir=asc&column=id&length=10&draw=2

I'm getting this error.
ErrorException: Undefined index:  in file C:\***\vendor\jamesdordoy\laravelvuedatatable\src\Traits\LaravelVueDatatableTrait.php on line 38

**Comment by jamesdordoy** [comment]
Hey @Jean45612,

Having looked into your undefined index issue. It is likely you do not have your columns defined correctly in your Laravel model class.

[See here for further details](https://github.com/jamesdordoy/Laravel-Vue-Datatable_Laravel-Package#use-the-trait).

The trait method checks which columns may be searched upon in the model.

If this is not the issue, please let me know and i will investigate further.

**Comment by Jean45612** [comment]
The problem was that I had not defined my columns in the model
Thanks
