### ISSUE TITLE
Reinitialize The Table

### ISSUE THREAD

**Issue by Gaxriel** [jamesdordoy/laravel-vue-datatable#39]
Hi, Thanks for a good job.
This is not an issue but a question.

Is there any method to reinitialize the laravel-vue-datatable ?

Thanks in advance

**Comment by jamesdordoy** [comment]
Hey @Gaxriel,

You can reinitialise the table by attaching a [Vue.js reference](https://vuejs.org/v2/api/#vm-refs) to the component.

After attaching the reference. The table can be reloaded using its underlying getData method e.g.

`this.$refs.datatable.getdata()`

More details can also be found on the [README](https://github.com/jamesdordoy/laravel-vue-datatable#reloading-the-table-manually)

Let me know if you need any further details.

**Comment by Gaxriel** [comment]
That's work well in my case.. Thanks a lot James.. Keep the good work.

**Comment by degeta10** [comment]
It's not working for me.

I get this error:
`TypeError: Cannot read property 'draw' of undefined`

Can you tell me why?
