### ISSUE TITLE
Pivot table

### ISSUE THREAD

**Issue by zsoltjanes** [jamesdordoy/laravel-vue-datatable#40]
Hello all! Can you give as an example how to use pivot table with this package?

**Comment by zsoltjanes** [comment]
Hi @jamesdordoy! I saw you code the pivot table extension, can you help me how to include the example component?

resource/js/app.js:
`
import DataTable from 'laravel-vue-datatable';
require('./bootstrap');
window.Vue = require('vue');
Vue.component('DataTableListCell', require('./components/DataTableListCell.vue').default);
Vue.use(DataTable);
const app = new Vue({
    el: '#app',
});
`

resource/js/components.DataTableListCell.vue
`<template>
  <ul>
    <li v-for="role in data.roles" :key="role.id">
      <a href="#">{{ role.name }}</a>
    </li>
  </ul>
</template>

<style scoped>
li {
  padding: 4px;
  margin: 0;
}

ul {
  margin: 0;
  padding: 0;
}
</style>

<script>
export default {
  props: {
    data: {}
  }
};
</script>`


`
<template>
  <main>
    <div class="container">
      <data-table :classes="classes" :columns="columns" url="data"></data-table>
    </div>
  </main>
</template>

<script>
export default {
  components: {
    DataTableListCell
  },
  data() {
    return {
      classes: {
        "table-container": {
          "table-responsive": true
        },
        table: {
          table: true,
          "table-striped": true,
          "table-main": true
        },
        "t-head": {},
        "t-body": {},
        "t-head-tr": {},
        "t-body-tr": {},
        td: {},
        th: {}
      },
      columns: [
        {
          label: "Roles",
          name: "roles",
          component: DataTableListCell
        }
      ]
    };
  }
};
</script>`

Error message:
Uncaught ReferenceError: DataTableListCell is not defined

**Comment by jamesdordoy** [comment]
Hey @zsoltjanes,

The pivot table example has been improved upon and I am currently putting together examples for all relationship types. Expect them to be available in the next day or two.

As for your above code, the `DataTableListCell` component is never defined. This is a component you have to make yourself to be injected into the table cell.

**Comment by zsoltjanes** [comment]
I figured it out, i had to import the component.

```
<script>
import DataTableListCell from './DataTableListCell.vue';
export default {
components: { DataTableListCell },
  data() {
```

**Comment by jamesdordoy** [comment]
You can find further details on relationship management on the docs now.

Hopefully this provides the functionality you need.

**Comment by zsoltjanes** [comment]
Yes thanks!
