### ISSUE TITLE
some tips to improve

### ISSUE THREAD

**Issue by mohammadgh1370** [jamesdordoy/laravel-vue-datatable#41]
Thanks for this package.

in front-end section and vue pckage:
Get a array of buttons for the view column(action columns).

in back-end and laravel package:
Ability to filter on relationships as well

**Comment by jamesdordoy** [comment]
Hey @mohammadgh1370,

I've pushed a new update to the Laravel package under version `0.3.1`. This will add relationship ordering and filtering.

As for getting an array of buttons in the client package. I can't see the benefit of adding this functionality as props really solve the issue of referencing large arrays of cells. Could you provide me with an example of how this might be required?

Thanks for the feedback though, hugely appreciated.

**Comment by jamesdordoy** [comment]
Closed due to inactivity

**Comment by coaradsupp** [comment]
hi, 
if set multiple button for example delete button, edit button ,... and so on
and set method or class or icon for button , ....

reslve it best package datatable

**Comment by jamesdordoy** [comment]
I am adding a C.R.U.D. example to the docs this week and it will provide an example for this functionality.
