### ISSUE TITLE
How to Add Image in Datatable?

### ISSUE THREAD

**Issue by crenata** [jamesdordoy/laravel-vue-datatable#42]
Thanks for nice work..!
But i have trouble for adding image in your datatable.
Please help me.

**Comment by jamesdordoy** [comment]
Hey @crenata,

I have added an example to the documentation that uses images in a datatable.

You can find it [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/injecting-dynamic-components).

Let me know if that clears any issues.

**Comment by crenata** [comment]
I already inject the component with static url, that's work.

but how to sending data url to the ImageComponent?

**Comment by jamesdordoy** [comment]
In your `ImageComponent`, accept the data prop e.g.

```
props: {
    data: {}
}
```

The row in question will be parsed into the component under this data prop and you can then manipulate the image src, alt attribute as required. e.g.

```html
<img :src="`/images/users/${data.id}.jpeg`">
```

**Comment by crenata** [comment]
Thank you very much for your help.

U're best teacher for me.

Keep making amazing ideas.

**Comment by darvinhuangg** [comment]
Even though the case has been closed, but I still will ask here since i face the similar problem.
how do you pass the value to the component? i dont get it on "The row in question will be parsed into the component" in previous answer.
Can you please advise or show the code?
