### ISSUE TITLE
TailwindCSS instead Bootstrap

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#43]
Is not an issue, but i have a question.
I know there is an option to override the bootstrap classes, but i really dont understand [this part](https://jamesdordoy.github.io/laravel-vue-datatable/examples/styling), where should i put the mixins/tailwind.js? i already working with tailwindCSS in my project.
is there another way to make it less laborious?

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

It's funny you bring this up. I had the exact same issue earlier working on my portfolio.

I agree it is laborious to create a mixin with each style defined on the table but i'm not sure there is a better approach at the moment as you are currently also able to dynamically change the column/table/row styles during events as they are props.

My approach was to create a wrapper component:

```html
<template>
    <data-table
        theme="dark"
        :url="url"
        :classes="classes"
        :columns="columns">
    </data-table>
</template>
```

```js
export default {
    props: {
        url: {

        },
        columns: {

        },
    },
    data() {
        return {
            classes: { 
                'table-container': {
                    'justify-center': true,
                    'w-full': true,
                    'flex': true,
                    'rounded': true,
                    'mb-6': true,
                    'shadow-md': true,
                },
                table: {
                    'text-left': true,
                    'w-full': true,
                    'border-collapse': true,
                },
                't-head': {
                    'text-grey-dark': true,
                    'bg-black': true,
                    'border-grey-light': true,
                    'py-4': true,
                    'px-6': true,
                },
                "t-body": {
                    'bg-grey-darkest': true,
                    
                },
                "t-head-tr": {
                    
                },
                "t-body-tr": {
                    'stripped-table': true,
                    'bg-grey-darkest': true,
                },
                "td": {
                    'py-4': true,
                    'px-6': true,
                    'border-b': true,
                    'border-grey-light': true,
                    'text-grey-light': true,
                },
                "th": {
                    'py-4': true,
                    'px-6': true,
                    'font-bold': true,
                    'uppercase': true,
                    'text-sm': true,
                    'text-grey-dark': true,
                    'border-b': true,
                    'border-grey-light': true,
                },
            }
        };
    },
}
```

That way the classes and props are segregated to a single component. Ideally i would love to add themes for different css frameworks but this is not something i'm familia with.

Apologies if this doesn't help.

**Comment by IsidroMar95** [comment]
yes, it's easier as you put it, but how can I customize the pagination, the search input and also the dropdown?
here's what I've been able to customize so far:
<img width="793" alt="Screenshot_2" src="https://user-images.githubusercontent.com/23019968/72562961-439cd400-3872-11ea-8311-789b8bc60763.png">

<img width="800" alt="Screenshot_3" src="https://user-images.githubusercontent.com/23019968/72562997-51eaf000-3872-11ea-8f7c-75aeeb260a5e.png">

 but I'd like it to look more or less like this:
<img width="793" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72563024-5fa07580-3872-11ea-8149-9f8fb3b7eb98.png">

i would live to override the whole component, I don't know how to customize input, dropdwon or pagination.

**Comment by jamesdordoy** [comment]
Ahh, here is a full example with everything:
> Table
```html
<template>
    <data-table
       :url="url"
        :classes="classes"
        :columns="columns">
        <span slot="filters" slot-scope="{ tableData, perPage }">
            <data-table-filters
                :classes="classes"
                :table-data="tableData"
                :per-page="perPage">
            </data-table-filters>
        </span>
    </data-table>
</template>
```

```js
export default {
    props: {
        url: {

        },
        columns: {

        },
    },
    data() {
        return {
            classes: { 
                'table-container': {
                    'justify-center': true,
                    'w-full': true,
                    'flex': true,
                    'rounded': true,
                    'mb-6': true,
                    'shadow-md': true,
                },
                table: {
                    'text-left': true,
                    'w-full': true,
                    'border-collapse': true,
                },
                't-head': {
                    'text-grey-dark': true,
                    'bg-black': true,
                    'border-grey-light': true,
                    'py-4': true,
                    'px-6': true,
                },
                "t-body": {
                    'bg-grey-darkest': true,
                    
                },
                "t-head-tr": {
                    
                },
                "t-body-tr": {
                    'stripped-table': true,
                    'bg-grey-darkest': true,
                },
                "td": {
                    'py-4': true,
                    'px-6': true,
                    'border-b': true,
                    'border-grey-light': true,
                    'text-grey-light': true,
                },
                "th": {
                    'py-4': true,
                    'px-6': true,
                    'font-bold': true,
                    'uppercase': true,
                    'text-sm': true,
                    'text-grey-dark': true,
                    'border-b': true,
                    'border-grey-light': true,
                },
            }
        };
    },
}
```
> Filters
```html
<template>
    <div class="flex w-full mt-4">
        <div class="flex  w-1/2">
            <div class="inline-block relative w-32">
                <select
                    @change="getData()"
                    v-model="tableData.length"
                    class="input-generic focus:outline-none focus:bg-white">
                    <option
                        :key="index"
                        :value="records"
                        v-for="(records, index) in perPage">{{records}}</option>
                </select>
                <div class="pointer-events-none absolute pin-y pin-r flex items-center px-2 pb-3 text-grey-darker">
                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                    </svg>
                </div>
            </div>
        </div>
        <div class="flex w-1/2 justify-end">
            <div class="flex w-1/2 justify-end"></div>
            <div class="flex w-1/2 justify-end">
                <text-input
                    name="name"
                    @input="getData()"
                    v-model="tableData.search"
                    placeholder="Search Table">
                </text-input>
            </div>
        </div>
    </div>
</template>
```

```js
export default {
    methods: {
        getData() {
            this.$emit("getData");
        }
    },
    props: [
        "tableData", "perPage"
    ]
}
```

I don't have a pagination example as i use custom components but you can easily implement you own using the pagination links provided by Laravel. The url is watched by the datatable component. So if you make changes to the pagination, filters, etc. you are able to reload the table

**Comment by jamesdordoy** [comment]
I will provided a full example for you in the morning otherwise based on your table.

**Comment by IsidroMar95** [comment]
wow thanks, i'll give it a try and i will let you know, this is the closest package that's let me use tailwindcss in the front.

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

You can find a Tailwind example [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/tailwind) on the docs.

It may require a little tweaking style-wise but hopefully is enough to get started with how you wanted the table to look.

Let me know if can help anymore.

**Comment by IsidroMar95** [comment]
thanks @jamesdordoy  i'll check it out and i'll let you know, but so far seems what is i'm looking for.

**Comment by IsidroMar95** [comment]
@jamesdordoy is working super cool. Thank you for your time and for example, it has been helpful to me, one last doubt:

1. Can the pagination [10,25,50] dropdown also be customized? how can I integrate it in TailwindDataTable component?
2. which icon are u using for the `DataTableDropdownCell` component.

here's what I've been able to customize so far:
<img width="960" alt="Screenshot_2" src="https://user-images.githubusercontent.com/23019968/72638575-52928d80-3929-11ea-962d-7f6377af9293.png">

**Comment by jamesdordoy** [comment]
@IsidroMar95 Awesome, i'm glad it helped.

1: Your filters slot can also take the `perPage` slot scope e.g.

```html
<div slot="filters" class="flex" slot-scope="{ tableData = {}, perPage = [] }">
```

You can then loop over the values and set a `v-model` directive on the on `tableData.length` to adjust the length of the table e.g.:

```html
<div class="relative">
    <select
        v-model="tableData.length"
        class="block appearance-none w-full border border-gray-200 text-gray-700 py-2 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
        <option
            :key="index"
            :value="records"
            v-for="(records, index) in perPage">{{records}}</option>
    </select>
    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
    </div>
</div>
```

To adjust the values in the perPage array, you can add a prop `per-page` to the datatable and specify your own. You can find out more [here](https://github.com/jamesdordoy/laravel-vue-datatable#datatable-props).

2: This one :) [https://fontawesome.com/icons/ellipsis-v?style=solid](https://fontawesome.com/icons/ellipsis-v?style=solid)

**Comment by jamesdordoy** [comment]
I've slightly updated the example on the docs to accommodate the table length.

Can be found [here](http://localhost:8080/laravel-vue-datatable/examples/tailwind).

Hopefully the you don't have the same issue with them.

**Comment by IsidroMar95** [comment]
Thank @jamesdordoy now works as expected except for one thing, i dont know why the `th` dont show the order icon, it need an extra config to show them?

<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72646045-be312680-393a-11ea-997d-16f13ae1c940.png">
anyway set them up in vue (app.js)
```

require("./bootstrap");

window.Vue = require("vue");
import DataTable from 'laravel-vue-datatable';
import { library } from '@fortawesome/fontawesome-svg-core'
import { faEllipsisV } from '@fortawesome/free-solid-svg-icons'
import { faSort } from '@fortawesome/free-solid-svg-icons'
import { faSortDown } from '@fortawesome/free-solid-svg-icons'
import { faSortUp } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

Vue.use(DataTable);
library.add(faEllipsisV)
library.add(faSort)
library.add(faSortDown)
library.add(faSortUp)


Vue.component('tailwind-data-table', require('./components/TDataTable/TailwindDataTable.vue').default)
Vue.component('font-awesome-icon', FontAwesomeIcon)

const app = new Vue({
    el: "#app"
});
```
But they don't show up

**Comment by jamesdordoy** [comment]
The column sort icons are really hard coded divs with styles attached so there should be no need for additional icon includes.

Ironically, i cannot get them to show up either on my personal projects. I don't know why they aren't showing but ill try and get this corrected tomorrow as well.

**Comment by IsidroMar95** [comment]
Thank you so much, I’ll wait to tomorrow ✌🏾. You don’t have any idea how much you helped me 🙏🏾

**Comment by jamesdordoy** [comment]
The column sorting icon issue should now be corrected.

You will need to update your npm package to 0.5.3.

Let me know if you still have any issue with the column sorting icons.

**Comment by IsidroMar95** [comment]
Thank you for all you effort. Now the sorts icons are shown correctly

**Comment by IsidroMar95** [comment]
Hi @jamesdordoy have you seen my last email? i sent you the table layout with TailwindCSS

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

I've seen it, apologies i've been at work. I will reply shortly.

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

I've updated the docs to align the tailwind example based upon yours.

There are a couple of differences but they are being caused by bootstrap clashing with some styles. I'll look to correct this at a later date but the table looks fine just using tailwind.

Thanks for the great looking example

**Comment by jamesdordoy** [comment]
Oh, and the new example has a correction to the styling of the table. Please update your npm package to 0.5.5 before using the implementation.

**Comment by IsidroMar95** [comment]
hi dude it's looks really nice, i sent you an email one more time.

**Comment by jamesdordoy** [comment]
Awesome, thanks dude. I have not received your email yet.

**Comment by IsidroMar95** [comment]
sorry my mistake, i've already sent it

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

I've thought about the issues you have been having with styling your table. I am thinking about pushing a new update to allow you to override the whole table and container using slot scopes so you can apply your own styles.

If you are happy with the current functionality i will close the issue, otherwise we can work to sort any other stying problems you may have by updating the package.

**Comment by IsidroMar95** [comment]
Hey @jamesdordoy  i think will be easy if like you say the component of the table passes like a slot, but let me layout the table like i want in responsive and i will send it to you tomorrow

**Comment by IsidroMar95** [comment]
hey @jamesdordoy i've already sent to you an email with the final layout, i hope that will be easy for you to implement.

**Comment by jamesdordoy** [comment]
Am i alright to close this issue now @IsidroMar95?

**Comment by IsidroMar95** [comment]
yeah, thank you so much.
