### ISSUE TITLE
search doesn't load the result data on the table

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#44]
I followed the instructions but the request seems not to return the correct data.
### model
```
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use JamesDordoy\LaravelVueDatatable\Traits\LaravelVueDatatableTrait;

class User extends Authenticatable
{
    use Notifiable,LaravelVueDatatableTrait;

    protected $laravelVueDataTableColumns = [
        'id' => [
            'searchable' => false,
        ],
        'name' => [
            'searchable' => true,
        ],
        'email' => [
            'searchable' => true,
        ]
    ];

    protected $laravelVueDataTableRelationship = [
        //
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```
### userController
```
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use JamesDordoy\LaravelVueDatatable\Http\Resources\DataTableCollectionResource;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $length = $request->input('length');
        $sortBy = $request->input('column');
        $orderBy = $request->input('dir');
        $searchValue = $request->input('search');

        $query = User::eloquentQuery($sortBy, $orderBy, $searchValue);

        $data = $query->paginate($length);

        return new DataTableCollectionResource($data);
    }
}
```
### component
```

<template>
    <data-table
        :columns="columns"
        url="usuarios">
    </data-table>
</template>

<script>
    export default {
        data() {
            return {
                columns: [
                    {
                        label: 'ID',
                        name: 'id',
                        orderable: true,
                    },
                    {
                        label: 'Name',
                        name: 'name',
                        orderable: true,
                    },
                    {
                        label: 'Email',
                        name: 'email',
                        orderable: true,
                    },
                ]
            }
        },
    }
</script>
```
when the page load the records in the table seems to work, even the pagination works, but when I do a search this is sent but does not seem to do the filtering since it returns the same information
<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72569395-fc1d4480-387f-11ea-96e1-789fb1bfb903.png">

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

The documentation was updated incorrectly on the last update.

The following was incorrect:

```php
protected $laravelVueDataTableColumns = [
    ...
];

protected $laravelVueDataTableRelationship = [
    ...
];
```

It should be:
```php
protected $dataTableColumns = [
    ...
];

protected $dataTableRelationships = [
    ...
];
```

The documentation has now been corrected [here](https://jamesdordoy.github.io/laravel-vue-datatable/laravel/trait)

Apologies for the confusion but this should solve the searching issue.

**Comment by LPABelgium** [comment]
Hi, 
Related to this subject, is there a way to disable the case sensitive ?

If the search is made with "test" but the value in model is "Test", no result is returned.
Or am I doing something wrong ?

**Comment by IsidroMar95** [comment]
> Hi,
> Related to this subject, is there a way to disable the case sensitive ?
> 
> If the search is made with "test" but the value in model is "Test", no result is returned.
> Or am I doing something wrong ?

You may doing something wrong, is working for me now
<img width="865" alt="Screenshot_2" src="https://user-images.githubusercontent.com/23019968/72629152-5ae0cd80-3915-11ea-80b1-636e47a66ae3.png">

**Comment by jamesdordoy** [comment]
Hey @LPABelgium,

There is no case sensitive constraint on the default searching. 

I'm not sure what would be causing that issue for you. You may want to check your database config or feel free to open a separate issue with some example code i can take a look at.

**Comment by LPABelgium** [comment]
Thanks @jamesdordoy.
It's probably 'cause I use Postgres as database...
I've update the FilderLocalData and it works like a charm ;)
Thanks for this package, really like it (and easier than many other tested before)
