### ISSUE TITLE
the documentation page isn't load

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#45]
It looks like the documentation page doesn't load, goes blank and shows some console errors
<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72628771-9cbd4400-3914-11ea-9620-bcf6167b8b81.png">

**Comment by jamesdordoy** [comment]
It's up on my computer at the moment.

Try clearing your cache but ill try and replicate the issue.

**Comment by IsidroMar95** [comment]
i already deleted the history data from chrome and tried with other browsers, the error is the same.

**Comment by jamesdordoy** [comment]
I've recompiled the docs and pushed them up again. I've check on a different pc and browser and it appears to be up.

Not sure what would be causing the issue as the docs use cache busting as well so the files are should be upto date.

**Comment by IsidroMar95** [comment]
it is working now, sorry for to many issues here. thanks
