### ISSUE TITLE
Reload() table payload empty [$ref.getData()]

### ISSUE THREAD

**Issue by arnoldenterina** [jamesdordoy/laravel-vue-datatable#51]
Hello, I am trying to reload the table after a certain data updated, but no payload is passed
Below is screenshot
![Screenshot_1](https://user-images.githubusercontent.com/49198189/73645668-ac79ae00-46b2-11ea-92fe-c53e5bce242a.png)

Below is my code snippet

`updateData(){`
`this.$refs.dttableref.getData()`
`}`

`<data-table ref="dttableref"  :columns="columns" url="/question/get"> </data-table>`

**Comment by jamesdordoy** [comment]
Hey @arnoldenterina,

I will attempt to replicate this tomorrow.

The payload is included in the default axios request so i wondered if you are using your own?

**Comment by arnoldenterina** [comment]
> Hey @arnoldenterina,
> 
> I will attempt to replicate this tomorrow.
> 
> The payload is included in the default axios request so i wondered if you are using your own?

Hello Good day Sir, I am confused of what you mean by using my own..

**Comment by arnoldenterina** [comment]
I follow this example in your table examples `https://jamesdordoy.github.io/laravel-vue-datatable/examples/basic` but I cannot find it to work in this.$refs.dttableref.getData() to reload data after I update it my database, for now I find working in this example : `https://jamesdordoy.github.io/laravel-vue-datatable/examples/own-data`

**Comment by arnoldenterina** [comment]
Thanks alot @jamesdordoy  🥂 😄

**Comment by jamesdordoy** [comment]
Apologies i haven't looked into this @arnoldenterina,

I've been under the weather with a bug. Will take a look at this ASAP.

**Comment by degeta10** [comment]
Just declare this in data:
```
 data() {
    url: "your_url",
    return { 
       tableProps: {
            params: {
            page: "2",
            search: "",
            length: 5,
            column: "id",
            dir: "asc",
            draw: 0
          }
        }
  }
```

And use this code to reload table.
` this.$refs.table.getData(this.url, this.tableProps);`
