### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by byjl** [jamesdordoy/laravel-vue-datatable#52]
https://jamesdordoy.github.io/laravel-vue-datatable/laravel/trait

The first property should be:
 **protected $dataTableColumns = [**

It took me a while to figure out why my search wasn't working.

Thanks, love the package so far.

**Comment by jamesdordoy** [comment]
Thanks @byjl, Great spot.

This should be corrected now.

Thanks for the kind words.
