### ISSUE TITLE
Download data from datatable

### ISSUE THREAD

**Issue by Jean45612** [jamesdordoy/laravel-vue-datatable#53]
Hi, I need to download all the datatable records, similar to a report. How can I get the data from the table?
Thanks

**Comment by IsidroMar95** [comment]
hi, i think this could be handled by backend e.g[ Laravel Excel  ](https://laravel-excel.com/) or [DomPDF](https://github.com/barryvdh/laravel-dompdf)

**Comment by Jean45612** [comment]
hi, i try, thanks

**Comment by jamesdordoy** [comment]
Closing as not a feature of this package.
