### ISSUE TITLE
acces to data[Array] inside of TableData Object

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#56]
how can i get the data array that is inside of TableData object?
i'm working on a export feature so i want to acces to the current data on the table so i need the id of the each element to do a query  to db.

![image](https://user-images.githubusercontent.com/23019968/74275627-d8f88000-4cd9-11ea-9f2d-146fd7c5a1b5.png)

i dont know how can i achieve this, i have the wrapper component.
![image](https://user-images.githubusercontent.com/23019968/74276316-1ad5f600-4cdb-11ea-812e-2262a0635b6f.png)

**Comment by jamesdordoy** [comment]
You can access the data property by adding a reference to the table. See [here](https://vuejs.org/v2/api/#vm-refs). You can access the data property using something like this `this.$refs.userDataTable.data.data`

**Comment by IsidroMar95** [comment]
is undefined
```
created() {
       console.log(this.$refs.userDataTable);
}
```

**Comment by IsidroMar95** [comment]
I forgot to add the ref to the table, now it works. Thank you.
