### ISSUE TITLE
How Can i add export button like excel, csv, pdf with datatables?

### ISSUE THREAD

**Issue by Robiussani152** [jamesdordoy/laravel-vue-datatable#57]
Is there any way to add the export button with the data table?

**Comment by IsidroMar95** [comment]
i think there is not any plan to add those features to the table, you can read the recomendations [here ](https://github.com/jamesdordoy/laravel-vue-datatable/issues/53)

**Comment by jamesdordoy** [comment]
@IsidroMar95 This is correct. IMO it is not worth adding additional code or dependencies to this plugin as the packages added may not be used or the code that i could implement wouldn't be as well tested or implemented as other packages that have been in the wild for much longer

@Robiussani152 apologies this isn't something i can help you with.

**Comment by inmanturbo** [comment]
This is very easy to do if you just import this plugin,
https://www.npmjs.com/package/vue-json-excel
