### ISSUE TITLE
How To Set Width Of a Column?

### ISSUE THREAD

**Issue by lypsisrudiansyah** [jamesdordoy/laravel-vue-datatable#58]

**Comment by jamesdordoy** [comment]
Hi @lypsisrudiansyah,

You can set the column width by using the `width` attribute. e.g.

```js
columns: [
    {
        label: 'Name',
        name: 'name',
        orderable: true,
        width: 20,
    },
    ....
]
```

You can see a full list of the column props [here](https://github.com/jamesdordoy/laravel-vue-datatable#column-props).

**Comment by lypsisrudiansyah** [comment]
i'm sorry @jamesdordoy ,

i've tried this, but on mine the width(column props) not working

`
columns: [
        {
          label: "Nama",
          name: "name",
          width: 30
        },
]
`

is there any or other solution ?

~Thanks In Advance

**Comment by jamesdordoy** [comment]
You can always add a parent element like a div and then target the specific table headers with your own css styles.

I'll try to replicate this issue.

**Comment by lypsisrudiansyah** [comment]
Ok, Thanks This Solution James, i will try it

**Comment by jamesdordoy** [comment]
I found an issue with the width value being parsed in the table. Expect a patch shortly.

**Comment by jamesdordoy** [comment]
Apologies attaching a bug and the previous comment was incorrect. 

I am not able to replicate this issue. The width style is being added using `0.5.7` and i've checked this in chrome dev tools. Would you mind inspecting the table header element to see if the width styling is being added? This could be a local caching issue also.

**Comment by lypsisrudiansyah** [comment]
![laravuedatatable](https://user-images.githubusercontent.com/52348378/74691882-45faa100-5217-11ea-9a6c-1b4372be04c7.PNG)

sorry @jamesdordoy ,
i've set the first column width by 50
and width styling seems like not added 

i don't really know how to fix or clear local cached

**Comment by jamesdordoy** [comment]
You can clear your local cache by right clicking the reload button when the dev tools are open. You will see additional options.

The table uses percent values for setting the column width :)

**Comment by lypsisrudiansyah** [comment]
Ow Ok @jamesdordoy , i've do it

but the header width styling still doesn't comes up
i'm sorry about this

**Comment by jamesdordoy** [comment]
No problem @lypsisrudiansyah,

Is this code for this in a public git repository? I can try to replicate the issue with your code then.

**Comment by lypsisrudiansyah** [comment]
sorry @jamesdordoy this code is private repository,

or Do I need to include certain code (configuration or usage)

or i have to update the package version ?
