### ISSUE TITLE
Multiple relationship column search not working.

### ISSUE THREAD

**Issue by Robiussani152** [jamesdordoy/laravel-vue-datatable#59]
I lave two belongsTo relationships in my model 
`protected $dataTableRelationships = [
        "belongsTo" => [
            'user' => [
                "model" => User::class,
                'foreign_key' => 'user_id',
                'columns' => [
                    'name' => [
                        'searchable' => true,
                        'orderable' => true,
                    ],
                ],
            ],
            'client' => [
                "model" => Client::class,
                'foreign_key' => 'client_id',
                'columns' => [
                    'company_name' => [
                        'searchable' => true,
                        'orderable' => true,
                    ],
                    'account_ref' => [
                        'searchable' => true,
                        'orderable' => true,
                    ]
                ]
            ]
        ],
    ];`

in vue file, I have integrated all as mentioned in the documentation, but I found an issue when I am searching it only works from my first relationship called `user`,  then I am going to debug the package source file and found one issue in `FilterBelongsToRelationships` class file that it return when only one array is execute. The previous code was like that 
`public function __invoke($query, $searchValue, $relationshipModelFactory, $model, $relationships)
    {
        $searchTerm = config('laravel-vue-datatables.models.search_term');

        if (isset($relationships['belongsTo'])) {
            foreach ($relationships['belongsTo'] as $tableName => $options) {

                if (! isset($options['model'])) {
                    throw new RelationshipModelNotSetException(
                        "Model not set on relationship: $tableName"
                    );
                }

                if (! isset($options['columns'])) {
                    throw new RelationshipColumnsNotFoundException(
                        "Columns array not set on relationship: $tableName"
                    );
                }

                $model = $relationshipModelFactory($options['model'], $tableName);

                return $query->orWhereHas($tableName, function ($query) use ($searchValue, $model, $options, $searchTerm) {

                    if (isset($options['columns'])) {

                        $tableName = $model->getTable();

                        foreach ($options['columns'] as $columnName => $col) {
                            if ($col[$searchTerm]) {
                                if ($columnName === key($options['columns'])) {
                                    $query->where("$tableName.$columnName", "like",  "%$searchValue%");
                                } else {
                                    $query->orWhere("$tableName.$columnName", "like",  "%$searchValue%");
                                }
                            }
                        }
                    }
                });
            }
        }

        return $query;
    }`
Then I just change the return statement when the loop ends now it's working perfectly. the modification code is 
`public function __invoke($query, $searchValue, $relationshipModelFactory, $model, $relationships)
    {
        $searchTerm = config('laravel-vue-datatables.models.search_term');

        if (isset($relationships['belongsTo'])) {
            foreach ($relationships['belongsTo'] as $tableName => $options) {

                if (! isset($options['model'])) {
                    throw new RelationshipModelNotSetException(
                        "Model not set on relationship: $tableName"
                    );
                }

                if (! isset($options['columns'])) {
                    throw new RelationshipColumnsNotFoundException(
                        "Columns array not set on relationship: $tableName"
                    );
                }

                $model = $relationshipModelFactory($options['model'], $tableName);

                $query->orWhereHas($tableName, function ($query) use ($searchValue, $model, $options, $searchTerm) {

                    if (isset($options['columns'])) {

                        $tableName = $model->getTable();

                        foreach ($options['columns'] as $columnName => $col) {
                            if ($col[$searchTerm]) {
                                if ($columnName === key($options['columns'])) {
                                    $query->where("$tableName.$columnName", "like",  "%$searchValue%");
                                } else {
                                    $query->orWhere("$tableName.$columnName", "like",  "%$searchValue%");
                                }
                            }
                        }
                    }
                });
            }
            return $query;
        }

        return $query;
    }`

**Comment by Robiussani152** [comment]
Found the same problem with `FilterHasManyRelationships` and `FilterBelongsToManyRelationships` class also.

**Comment by jamesdordoy** [comment]
Hey @Robiussani152,

This issue relates to the other repository so it will be dealt with there.
