### ISSUE TITLE
inject dynamic components (button example)

### ISSUE THREAD

**Issue by timoteo7** [jamesdordoy/laravel-vue-datatable#6]
I try to inject dynamic components as an example (button component example),
but it did not work, (copying the code of README)

could you put more details on how this works?
example that shows some data of the line that is clicked?

**Comment by jamesdordoy** [comment]
Hey,

I can see why the README is confusing with some examples as they do not provide full code.

I'll look to create some specific examples before next week detailing how to use dynamic components etc.

Thanks for creating an issue.

**Comment by jamesdordoy** [comment]
Documentation can now be found [here](https://jamesdordoy.github.io/laravel-vue-datatable/).

Further examples will be added over the coming days.
