### ISSUE TITLE
Resource Collection Implementation

### ISSUE THREAD

**Issue by BrandonMause** [jamesdordoy/laravel-vue-datatable#60]
James,

I am so excited to use this.  I set everything up in my laravel 6 app and am getting the dreaded
"TypeError: Cannot read property 'draw' of undefined" error.  I know it's user error on my part.  I'm using laravelas I mentioned and I believe I installed everything correctly.  I think that the problem is with my Collection Resource implementation.  I am new to collection resources.  Would you happen to have an example Model, Controller, and Collection Resource that I could reference?

I saw in another issue you referenced CRUD videos you made, any videos at all would be helpful.  
Thanks so much!
Brandon

**Comment by jamesdordoy** [comment]
Hey @BrandonMause,

I have an example repository [here](https://github.com/jamesdordoy/Laravel-Vue-Datatable-Example) that includes the above example Model, Controller and shows how to use the Collection Resource.

I still need to finish off the videos for installation and C.R.U.D. for this package but at the moment I don't have the spare time to put these together.

I'll see what i can do in the near future to provide more detailed examples and installation instructions such as maybe a Medium article or finishing off those videos.

Let me know if i can provide any more specific help,

**Comment by jamesdordoy** [comment]
Closed due to inactivity.
