### ISSUE TITLE
Add Component in column label

### ISSUE THREAD

**Issue by Jean45612** [jamesdordoy/laravel-vue-datatable#61]
Hi James, I have a question, I need to add a component in the label column. I don't know if it can be done.

![image](https://user-images.githubusercontent.com/58889580/75802929-94498d00-5d4b-11ea-92bc-0acc94ea9ff4.png)

Thanks

**Comment by jamesdordoy** [comment]
Hey @Jean45612,

This isn't currently possible but i will try to push an update today to add this functionality.

**Comment by Jean45612** [comment]
Hi James, thanks. I'll be waiting.

**Comment by jamesdordoy** [comment]
Hey @Jean45612,

To confirm you are trying to add a component to the `<thead>` area of the table?

**Comment by Jean45612** [comment]
Hi James, yes i try to add component to the <thead>

**Comment by jamesdordoy** [comment]
Hey @Jean45612,

I've pushed a new update `0.5.10` that should allow you to create the example above.

You can find more details [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-table-header).

Let me know if you need any further examples or if something isn't working correctly.

**Comment by Jean45612** [comment]
Thanks
