### ISSUE TITLE
Pagination next and prev text change

### ISSUE THREAD

**Issue by mucskaati** [jamesdordoy/laravel-vue-datatable#63]
Hello,

1. Is there any solution for changing text (Next, Prev) in default pagination buttons?
When I tried to use custom pagination according to documentation the next button didnt work.

Thanks.

**Comment by jamesdordoy** [comment]
Hey @mucskaati,

This can now be achieved by using the table's `translate` prop. You can find details [here](https://github.com/jamesdordoy/laravel-vue-datatable#datatable-props).

**Comment by mucskaati** [comment]
Thank you so much :) @jamesdordoy
