### ISSUE TITLE
Is there any way to delay the search/filter event?

### ISSUE THREAD

**Issue by timmy1420** [jamesdordoy/laravel-vue-datatable#64]
Reason: Every keystroke causes the server-side to handle a request. Mostly with sql queries. If we can have a delay after a keystroke e.g. 2.5, the search/filter event would trigger after the user is done typing.

**Comment by timmy1420** [comment]
Meanwhile I have been doing some code edits myself. @jamesdordoy Are you willing to approve my PR? I need this solution for a project I'm working on. Although, the code I wrote might not be 100% cool to work with I think, but feel free to edit it :)

Git commit here:
https://github.com/timmy1420/laravel-vue-datatable/commit/7361e217bca5a6730c4b1f8616406c90346dfc18

**Comment by jamesdordoy** [comment]
Hey @timmy1420,

I will merge your PR and make some changes just to tidy up new debounce functionality.

Thanks for the PR.

**Comment by timmy1420** [comment]
@jamesdordoy Also thank you very much for creating this package.

**Comment by jamesdordoy** [comment]
@timmy1420 no worries,

I've published a new update `0.5.9` that adds the debounce functionality.

The prop is named `debounce-delay` and is a number with a default value of 0 as you suggested.

Thanks for the PR again.

**Comment by timmy1420** [comment]
Alright @jamesdordoy. Thank you for implementing it for us within a day ^_^. I will test it out later. Can I close this issue afterwards?

**Comment by jamesdordoy** [comment]
Yeah, feel free when you're happy with the functionality.

**Comment by timmy1420** [comment]
Alright

**Comment by jamesdordoy** [comment]
Hey @timmy1420,

I pushed some bug fixes caused by moving to the debounce method. Please update your package to `0.5.10` when you test the functionality :)

**Comment by timmy1420** [comment]
@jamesdordoy This feature is working very nicely. Thank you for taking your time implementing this. I'm closing this issue as being *solved*.

**Comment by IsidroMar95** [comment]
hey bro @jamesdordoy  how this feature works? i'm interested on the same situation

**Comment by timmy1420** [comment]
> hey bro @jamesdordoy how this feature works? i'm interested on the same situation

According to the README https://github.com/jamesdordoy/laravel-vue-datatable#api, there is a debounce-delay prop.

E.g:

``` js
<data-table
            ...
            url="/datatable/users"
            :per-page="perPage"
            :columns="columns"
            :order-by="orderBy"
            :order-dir="orderDirection"
            :debounce-delay=2000
            ...">
        </data-table>
```

The debouce-delay is in milliseconds so 2000 is 2 seconds.
