### ISSUE TITLE
Execute method in component of datatable

### ISSUE THREAD

**Issue by Jean45612** [jamesdordoy/laravel-vue-datatable#66]
Hi, I usually use refs to execute methods on my child components. But in this case how could I assign ref to a component that is inside my datatable.

**Comment by jamesdordoy** [comment]
Hey @Jean45612,

I assume you mean a component injected into the table inside a `column` object?

**Comment by Jean45612** [comment]
Yes, i have a component injected into the table inside a column object. I need execute function inside that component, but in this case, i don't know how to do.
![image](https://user-images.githubusercontent.com/58889580/76691204-7830d000-6616-11ea-9491-53c353caf5ec.png)

**Comment by timmy1420** [comment]
> Yes, i have a component injected into the table inside a column object. I need execute function inside that component, but in this case, i don't know how to do. What happens is that I want to reload the component, i used this. $ Refs.myTable.getData (), but that only updates the records. So I wanted to execute a function that has the component.
> ![image](https://user-images.githubusercontent.com/58889580/76691204-7830d000-6616-11ea-9491-53c353caf5ec.png)

Hi @Jean45612.

What you could try is by emitting the method from the parent component (which is the datatable) or just going through the DOM.

This how I did it:

1.
``` js
this.$emit('updateValues', {
       ...
        'status': this.status_param ? this.status_param : null,
       ...
});
```

or

``` js
this.$root.$children[0].reloadTable();
```

**Comment by jamesdordoy** [comment]
Hi @Jean45612,

From testing i did around the issue in march i wasn't able to find a nice solution for this.

Apologies,

James
