### ISSUE TITLE
How to change date format like (DD/MM/YYYY) using moment

### ISSUE THREAD

**Issue by hurokan** [jamesdordoy/laravel-vue-datatable#68]
![date_formate_issue](https://user-images.githubusercontent.com/23186807/76744859-19e32900-679f-11ea-8277-a8e1eeb4cf9b.PNG)

**Comment by jamesdordoy** [comment]
Hi @hurokan,

See [here](https://github.com/jamesdordoy/laravel-vue-datatable/issues/28).

**Comment by jamesdordoy** [comment]
Closed due to inactivity
