### ISSUE TITLE
Documentation examples "Network Error" issue

### ISSUE THREAD

**Issue by bomjastik** [jamesdordoy/laravel-vue-datatable#73]
Hello. Thanks for the great component! But examples on the documentation site doesn't work.
I'm getting "Error: Network Error".

![console](https://user-images.githubusercontent.com/1671780/77644696-19e6e400-6f6a-11ea-81d5-cab69db39991.jpg)

![network](https://user-images.githubusercontent.com/1671780/77644699-1b181100-6f6a-11ea-8eba-5159f8a1b8f5.jpg)

**Comment by jamesdordoy** [comment]
They should be back up now. Apologies, was an `.env` issue.

Thanks for letting me know
