### ISSUE TITLE
Footers

### ISSUE THREAD

**Issue by inmanturbo** [jamesdordoy/laravel-vue-datatable#80]
Great component!
How do you recommend adding footers with like say, perPage totals for a column with a float or integer amount. Do you have a slot for the footer? Also adding perPage : [15,25,80] in props or data seems to have no affect? 

Cheers!

**Comment by jamesdordoy** [comment]
Hi @inmanturbo,

See [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters).

**Comment by inmanturbo** [comment]
that doesn't quite answer my question but I think I inderstand why. I'm going to close this as more related to a particular use case than the component itself. I don't want to clutter the issues. maybe over time the docs will grow in detail. Thank you.
