### ISSUE TITLE
How do I set the search field value?

### ISSUE THREAD

**Issue by EspetoRx** [jamesdordoy/laravel-vue-datatable#81]
Hi, It's me again.

I'm sorry for bothering you so much...
Well, I have a vue route with params, I would like to pass the param to the datatable as it was in search field, how can I do this?

Thx for the great job.

**Comment by jamesdordoy** [comment]
Hi @EspetoRx,

You will need to extract the value from the URL using a getURLParam function. You should be able to google that and find a result.

To pass the value to the search field, you will need to override the top filters using a slot, see [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters).

Just set the value of the input and it should update accordingly. If not try a v-model as i havent tested this.

James
