### ISSUE TITLE
Relationships -> BelongsTo when it's the same table

### ISSUE THREAD

**Issue by Al3xR0** [jamesdordoy/laravel-vue-datatable#82]
I am having a parent relation in the same table, with an parent_id from the same table, and I'm getting this error: **SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias ...:**

```
class Category extends Model {

....

   protected $dataTableRelationships = [
        "belongsTo" => [
            'parent' => [
                "model" => \App\Category::class,
                'foreign_key' => 'parent_category_id',
                'columns' => [
                    'name' => [
                        'searchable' => true,
                        'orderable' => true,
                    ],
                ],
            ],
        ],
    ];

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_category_id', 'id');
    }

....

}
```

**Comment by mucskaati** [comment]
I have the same problem :/ @jamesdordoy

**Comment by mucskaati** [comment]
Hello @Al3xR0 ,

I found a solution, of course if your problem still persists.
You just need to use classic statement `$data = Employee::with('parent')->paginate($length);` and not  ` $query = Employee::eloquentQuery($sortBy, $orderBy, $searchValue, [
            "parent",
        ]);

        $data = $query->paginate($length);
`
In my case it was a solution.
I hope in your case it will be also...

**Comment by jamesdordoy** [comment]
Hi @mucskaati 

Yes you can use your own eloquent statements to create the query but you will also have to manage the sorting, filtering etc. with your own code.

@Al3xR0 ill have a look into self referencing tables this weekend and see if there is any issue being caused by the generated query.

Thanks

**Comment by mucskaati** [comment]
@jamesdordoy  is something new about this enhancement? thanks.
