### ISSUE TITLE
Search from other areas like header or in the sidebar

### ISSUE THREAD

**Issue by zarpio** [jamesdordoy/laravel-vue-datatable#85]
How to move the search input box to the header of the site if needed?

![image](https://user-images.githubusercontent.com/112050/87852458-963b7380-c91b-11ea-909b-fe7b8603ed63.png)

**Comment by jamesdordoy** [comment]
Hi @zarpio,

This is possible by overriding the table filters using a slot, see [here](https://jamesdordoy.github.io/laravel-vue-datatable/examples/override-filters).

You just need to pass that value as a prop to the table and it will update.

James
