### ISSUE TITLE
your commnet for this datatable

### ISSUE THREAD

**Issue by mohammadgh1370** [jamesdordoy/laravel-vue-datatable#87]
please comment for this datatable ????

https://github.com/mohammadgh1370/laravuedatatable

[demo](http://datatable.ihweb.ir/)

**Comment by jamesdordoy** [comment]
My comment is that it looks good and you should release it as your own package. I dont have the time at the moment to make large changes to the API. I am looking to rebuilt the component over the coming months.

James
