### ISSUE TITLE
Property: addFiltersToUrl not working, missing implement a method updateParameters

### ISSUE THREAD

**Issue by metrey** [jamesdordoy/laravel-vue-datatable#89]
In `DataTable.vue` miss to implement method `updateParameters` and also `checkParameters`

```
if (this.addFiltersToUrl) {
	this.updateParameters(this.tableProps);
}
```

**Comment by jamesdordoy** [comment]
Hi @metrey,

Please create a PR.

I'm not sure what the issue is with the code you have presented?

James
