### ISSUE TITLE
Loading Animation is keeps on loading

### ISSUE THREAD

**Issue by usmanfarooqch** [jamesdordoy/laravel-vue-datatable#90]
Hi there, thanks for creating such a nice datatable, it helped me alot, but i am not able to figure out why these two properties doesnt have any effect, my page is keeps on showing loading animation 

you may also find it on your page as well
https://jamesdordoy.github.io/laravel-vue-datatable/examples/loading-animations

I will be grateful if you can tell me whats the issue? by the way i haeve added these two properties in my datatable component
    @loading="isLoading = true"
    @finishedLoading="isLoading = false"

**Comment by usmanfarooqch** [comment]
> Hi there, thanks for creating such a nice datatable, it helped me alot, but i am not able to figure out why these two properties doesnt have any effect, my page is keeps on showing loading animation
> 
> you may also find it on your page as well
> https://jamesdordoy.github.io/laravel-vue-datatable/examples/loading-animations
> 
> I will be grateful if you can tell me whats the issue? by the way i haeve added these two properties in my datatable component
> @Loading="isLoading = true"
> @finishedLoading="isLoading = false"

Guys, after hours of thinking lol, i have find out that, it should be  @finished-loading="isLoading = false" instead of  @finishedLoading="isLoading = false"

**Comment by jamesdordoy** [comment]
@usmanfarooqch,

Thank you for bringing this to my attention. I will update the docs ASAP.

Thanks

**Comment by LeonBuchner** [comment]
Thanks for the hint.
Its still wrong in the docs
