### ISSUE TITLE
Table is not responsive

### ISSUE THREAD

**Issue by uisumo** [jamesdordoy/laravel-vue-datatable#93]
Hi,

Could anyone guide me on how to achieve table responsiveness using this component?

I used these classes by default. But the table is not responsive.

`default: () => ({

                "table-container": {
                    "table-responsive": true,
                },
                "table": {
                    "table": true,
                    "table-striped": true,
                    "border": true,
                    "tableclass": true,
                },
                "t-head": {},
                "t-body": {},
                "td": {},
                "th": {},
            }),`

Appreciate your suggestions, please.

Thanks,
- Adi

**Comment by jamesdordoy** [comment]
Closing as the UI for the table will be moving to Tailwind before the end of October. 

A responsive table will be available upon release or will follow shortly after,
