### ISSUE TITLE
Failed for prop "data". Expected Object, got Array

### ISSUE THREAD

**Issue by devemtv** [jamesdordoy/laravel-vue-datatable#94]
Hi, i have a problem, i try to implement the component but i am getting this error... 

`Invalid prop: type check failed for prop "data". Expected Object, got Array`

How should the data be passed to the props data?

I await your response, thanks.

**Comment by jamesdordoy** [comment]
Hi @devemtv,

The table expects the data from the backend to be paginated using the `DataTableCollectionResource` provided on the backend package.

See [here ](https://jamesdordoy.github.io/laravel-vue-datatable/laravel/controller-resource )for more details.

Thanks,

James
