### ISSUE TITLE
Unknown custom element: <data-table>

### ISSUE THREAD

**Issue by EmperorKonstantin** [jamesdordoy/laravel-vue-datatable#95]
I'm running into the strangest issue. 

I followed your docs to a T and I'm getting this error in console. I either missed something terribly obvious or there's a bug. 

I have both the NPM and Laravel composer packages installed. It's the only vue package I have so far that's failing to load. 

Chrome Console:
app.js:32558 [Vue warn]: Unknown custom element: <data-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <UsersIndexDatatable> at resources/js/components/UsersDatatable.vue
       <Root>

**Comment by jamesdordoy** [comment]
Hi @EmperorKonstantin,

That is strange, i'm unable to replicate your issue locally. As a guess, i'd assume you forgot to add this line to your app.js file:

`Vue.use(DataTable);`

Are you using the package in a standard Laravel set up or do you have a separate code base for your front-end? Ill try to replicate accordingly.

Thanks,

James

**Comment by EmperorKonstantin** [comment]
It's in a webpack app.js file like so:

![image](https://user-images.githubusercontent.com/3018990/93814976-ecc67600-fc1a-11ea-9696-0ec2ac331add.png)

**Comment by EmperorKonstantin** [comment]
Nevermind, I brainfarted because you named your example controller method index. There should be one method called index  that returns a view and one method called datatable that returns a URL that the vuejs-datatable could query.

**Comment by satria1697** [comment]
i got the same problem,

Edge console "[Vue warn]: Unknown custom element: <data-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option"

should i install laravel package too? or i can skip that part? thanks

**Comment by EmperorKonstantin** [comment]
@satria1697, you definitely want the laravel package installed as well. 

Here's what you should have in app.js:

`js
require('./bootstrap');

import Vue from 'vue';

import DataTable from 'laravel-vue-datatable';
Vue.use(DataTable);
Vue.component('datatable', require('./components/Datatable').default);
`

**Comment by satria1697** [comment]
kay, ill try it, thanks

**Comment by satria1697** [comment]
i use vue-cli, is there anything i can do? still get the same problem

**Comment by rashed50702** [comment]
> i use vue-cli, is there anything i can do? still get the same problem

I am facing same problem. Did you find any solution?

**Comment by satria1697** [comment]
![Screenshot_2020-12-23-18-23-28-005_com.github.android.png](https://user-images.githubusercontent.com/39475953/102991595-1d84b700-454c-11eb-847e-a7e36ca2995e.png)
i use it like this

**Comment by EmperorKonstantin** [comment]
I'm marking it as resolved.
