### ISSUE TITLE
Pass token into the headers

### ISSUE THREAD

**Issue by dibet** [jamesdordoy/laravel-vue-datatable#97]
Hi, it is a fantastic plugin but i need to pass a bearer token into the headers and i dont see any way to do it.
Can you help me?

**Comment by jamesdordoy** [comment]
Hi @dibet,

I have added a prop to the datatable so headers can be passed in however but there seems to be an bug with a duplicate request running at the moment returning a 204 success.

I'll look to fix this ASAP and then release for you.

Regards,

James

**Comment by dibet** [comment]
Fantástico. Thanks

**Comment by jamesdordoy** [comment]
Hi @dibet,

You can now add request headers to the axios instance. See [here ](https://github.com/axios/axios#request-config)how they are configured.

I have also updated the [documentation ](https://jamesdordoy.github.io/laravel-vue-datatable/props/table)accordingly.

Thanks,

James
