### ISSUE TITLE
Transform column/cell value 

### ISSUE THREAD

**Issue by caredev** [jamesdordoy/laravel-vue-datatable#98]
Is there any way to transform the visible value of the cell?

Let's say that you have a table that returns a list of a client's orders. with the following structure:
## Current output
|#|Reference|Subtotal|Taxes|Total|
|-|-|-|-|-|
|1|PO-20027|50.45|10.00|60.45|
|2|PO-20038|20.00|5.00|25.00|

Is it possible to call a function that transformates the desired columns such as Subtotal, Taxes and Total so they transform the value to a human readable value?

## Desired output
|#|Reference|Subtotal|Taxes|Total|
|-|-|-|-|-|
|1|PO-20027|50.45 €|10.00 €|60.45 €|
|2|PO-20038|20.00 €|5.00 €|25.00 €|

In this example it's just adding the euro symbol, but it might be anything else like a dynamic "X seconds/min/days/weeks... ago" for datetime values.

If it is not implemented there should be a "manipulate" option for the columns that receives as an attribute the column itself the cell to be formated.

## Current solution (not ideal)
Right now this can be achieved by using a dynamic component, but I think it's over complicated.

```vue 
{
          label: 'Subtotal',
          name: 'subtotal',
          component: Vue.component('dt-dyn-cell', resolve => {
            resolve({
              props: {
                data: {},
                name: {},
              },
              template: `<span v-html="subtotal"></span>`,
              computed: {
                subtotal() {
                  return this.data.subtotal + ' &euro;'
                },
              },
            })
          }),
        },
```

**Comment by jamesdordoy** [comment]
Hi @caredev,

You PR has been published under 0.5.14.

I agree, creating a separate component could be considered over kill for formatting a value but i guess it depends how often you want to format them. I appreciate you can abstract that to a function and then just import it where necessary but that dosn't always read as nicely as nesting components. Each to their own but i appreciate the PR and think its a great addition.

Thanks again

**Comment by caredev** [comment]
Thank you for accepting this PR.
I am working in some other improvements for my project I hope some of them are interesting enough to be merged.

**Comment by jamesdordoy** [comment]
Hi @caredev,

Am i ok to close this issue?

James

**Comment by caredev** [comment]
Thanks
